name: Sleep Health CI Pipeline (MLOps Level 2)

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Kodları çek
    - uses: actions/checkout@v3

    # 2. Python 3.11 Kurulumu (Senin bilgisayarınla eşitledik)
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    # 3. Kütüphaneleri yükle
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install dvc pytest pandas scikit-learn

    # 4. Test verisini oluştur
    - name: Generate Dummy Data for Testing
      run: |
        python -c "import pandas as pd; import numpy as np; import os; np.random.seed(42); os.makedirs('data', exist_ok=True); df = pd.DataFrame({'Sleep Duration': np.random.normal(7, 1.5, 100), 'Heart Rate': np.random.normal(70, 10, 100)}); df['Stress Level'] = 10 - (df['Sleep Duration']*0.8) + (df['Heart Rate']*0.05); df.to_csv('data/sleep_health.csv', index=False); print('Test verisi olusturuldu.')"

    # 5. Testleri Çalıştır
    - name: Run Tests
      run: |
        python -m pytest tests/